import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
  caixa: {
    height: "100%",
    width: "100%",
    backgroundColor: "#fff",
  },
  container0: {
    marginBottom: 0,
    marginTop: 1,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 35,
    marginRight: 30,
    borderRadius: 10,
    padding:0,
  },
    container: {
    marginBottom: 0,
    marginTop: 1,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 35,
    marginRight: 30,
    borderRadius: 10,
    padding:0,
  },
  container_row: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 5,
    marginBottom: 10,
    fontSize: 5,
    textAlign: "center",
    width: "48%",
    borderRadius: 10,
    backgroundColor: "#e6aa65",
  },

  texto: {
    fontSize: 16,
    color: "white",
    textAlign: "center",
  },
  imagem: {
    width: "95%",
    height: "30%",
    marginTop: 40,
    padding: 20,
    borderRadius: 6,
    marginTop: 50,
    marginLeft: 35,
    marginRight: 30,
  },
  btn: {
    backgroundColor: "#ff8C00",
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    borderRadius: 6,
    width: 90,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  btn1: {
    backgroundColor: "#ff8C00",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 136,
    padding: 10,
    borderRadius: 6,
    width: 90,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  imagemCurso: {
    width: 50,
    height: 50,
    borderRadius: 30,
  },
  container_normal: {
    backgroundColor: "#e6aa65",
    marginBottom: 15,
    marginRight: 10,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 11,
    borderRadius:10,
  },
  abertura: {
    alignItems: "center",
    marginBottom: 20,
    marginTop: 20,
  },
  portifolioImg: {
    width: 150,
    height: 150,
    borderRadius: 80,
    marginTop: 2,
    marginBottom: 10,
    display: "flex",
    alignItems: "center",
  },
  portifolioImg2: {
    width: 230,
    height: 250,
    borderRadius: 10,
    marginTop: 20,
    display: "flex",
    alignItems: "center",
  },
  textoCard: {
    padding: 5,
    color: "white",
    fontSize: 17,
    alignItems: "center",
    justifyContent: "center",
    marginLeft:19,
  },
  textoCard55: {
    padding: 5,
    color: "white",
    fontSize: 17,
    alignItems: "center",
    justifyContent: "center",
    marginLeft:80,
  },
  textoCard3: {
    color: "#fff",
    padding: 5,
    color: "black",
    fontWeight: "bold",
    fontSize: 15,
    alignItems: "center",
    justifyContent: "center",
    marginLeft:13,
  },
  tituloCard: {
    color: "#fff",
    fontSize: 15,
    marginTop: 1,
    marginBottom: 5,
    padding: 0,
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
  },
  tituloCard1: {
    fontWeight: "bold",
    color: "#fff",
    fontSize: 20,
    marginTop: 1,
    marginBottom: 5,
    padding: 0,
    alignItems: "center",
    justifyContent: "center",
    marginLeft:15,
  },
  tituloCard3: {
    color: "#fff",
    fontSize: 16,
    marginTop: 1,
    marginBottom: 5,
    padding: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    backgroundColor: "#e6aa65",
    marginBottom: 5,
    marginRight: 10,
    marginLeft: 13,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 5,
    padding: 10,
    width: "90%",
  },
  titulo: {
    color: "#ff8C00",
    fontSize: 30,
    textAlign: "center",
    marginTop: 20,
    marginBottom: 5,
    fontWeight: "bold",
  },
  labels: {
    fontWeight: "bold",
    fontSize: 18,
    padding: 5,
    marginTop: 5,
    marginRight: 10,
    marginLeft: 8,
  },
  labelComentarios: {
    color:"#fff",
    fontWeight: "bold",
    fontSize: 18,
    padding: 5,
    marginTop: 5,
    marginRight: 10,
    marginLeft: 8,
  },
  textArea: {
    backgroundColor: "#fff",
    // width: "95%",
    borderRadius: 8,
    height: 100,
    marginRight: 10,
    marginLeft: 10,
  },
});

export default styles;
